### ISSUE TITLE
Error running webassembly command

### ISSUE THREAD

**Issue by vinibern5** [macabeus/klo-gba.js#4]
After running the `sh ./shellscript/compile-webassembly.sh` command, I've got the following error:

```
sh ./shellscript/compile-webassembly.sh 
./shellscript/compile-webassembly.sh: 1: ./shellscript/compile-webassembly.sh: function: not found
./shellscript/compile-webassembly.sh: 2: local: not in a function
``` 

The script successfully executed with `bash ./shellscript/compile-webassembly.sh`

PS: I've got this error on Ubuntu 18.04 LTS.

**Comment by macabeus** [comment]
Nice. [This answer](https://stackoverflow.com/a/12469057/3440266) explain why this error happed.

Maybe we should change the readme saying to use `bash` instead of `sh`, then we can use some bash features (like `function` and `local` keywords) to write a better code.
